openapi: 3.0.0
info:
  title: Account Management API
  version: 1.0.0
components:
  schemas:
    Amount:
      type: object
      properties:
        account_id:
          type: string
          format: uuid
        amount:
          type: integer
      required:
        - account_id
        - amount
    Balance:
      type: object
      properties:
        balance:
          type: integer
      required:
        - amount
    MaxTransactionVolume:
      type: object
      properties:
        maxVolume:
          type: integer
        accounts:
          type: array
          items:
            type: string
            format: uuid
  examples:
    PositiveAmount:
      value:
        account_id: '0afd02d3-6c59-46e7-b7bc-893c5e0b7ac2'
        amount: 7
    NegativeAmount:
      value:
        account_id: '5ae0ef78-e902-4c40-9f53-8cf910587312'
        amount: -4
    PositiveBalance:
      value:
        balance: 10
    MaxTransactionVolumeExample:
      value:
        maxVolume: 4
        accounts: [
          "44a92331-a533-4dd3-82e3-3ff75219e33b",
          "7c9be9e8-a6df-4f43-9a44-38c10ad0de4a"
        ]
paths:
  /amount:
    post:
      summary: Updates account balance with amount.
      parameters:
        - in: header
          name: Transaction-Id
          schema:
            type: string
            format: uuid
          example: 'cf479136-0a5b-42ad-a16c-26d9eda3b4aa'
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Amount'
            examples:
              PositiveAmount:
                $ref: '#/components/examples/PositiveAmount'
              NegativeAmount:
                $ref: '#/components/examples/NegativeAmount'

      responses:
        '200':
          description: Operation accepted.
        '400':
          description: Mandatory body parameters missing or have incorrect type.
        '405':
          description: Specified HTTP method not allowed.
        '415':
          description: Specified content type not allowed.

  /balance/{account_id}:
    get:
      summary: Returns current account balance.
      parameters:
        - name: account_id
          in: path
          required: true
          description: Account ID.
          schema:
            type: string
            format: uuid
          example: '5ba6e1b0-e3e7-483a-919a-a2fc17629a90'
      responses:
        '200':
          description: Account balance.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
              examples:
                PositiveBalance:
                  $ref: '#/components/examples/PositiveBalance'
        '404':
          description: Account not found.
  /transaction/{transaction_id}:
    get:
      summary: Returns transaction details.
      parameters:
        - name: transaction_id
          in: path
          required: true
          description: Transaction ID.
          schema:
            type: string
            format: uuid
          example: '023d2024-24bc-42c9-ab24-689eef6ea0f9'
      responses:
        '200':
          description: Transaction details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
              examples:
                PositiveBalance:
                  $ref: '#/components/examples/PositiveBalance'
        '404':
          description: Transaction not found
  /max_transaction_volume:
    get:
      summary: Returns accounts with max number of transactions.
      responses:
        '200':
          description: Accounts with max number of transactions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaxTransactionVolume'
              examples:
                MaxTransactionVolumeExample:
                  $ref: '#/components/examples/MaxTransactionVolumeExample'
